FROM golang:1.23-alpine

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download


COPY . .

# Install Swag CLI for generating API documentation
RUN go install github.com/swaggo/swag/cmd/swag@latest

# Generate Swagger API documentation
RUN swag init

RUN go mod vendor

RUN go build -o /api

RUN go install github.com/air-verse/air@v1.52.3


EXPOSE 8080

CMD ["air"]
