services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ai-mentor-api
    hostname: ai-mentor-api
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - ai-mentor
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    expose:
      - 8080
    # depends_on:
    #   - db
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=ai-mentor

    restart: unless-stopped 

    volumes:
      - .:/app:cached

  # db:
  #   image: postgres:15-alpine
  #   ports:
  #     - "5433:5433"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=ai_mentor
  #   restart: unless-stopped 

  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:

networks:
  ai-mentor:
    driver: bridge
