server:
  port: 8080
  read_timeout: 60
  write_timeout: 60

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: ai_mentor
  ssl_mode: disable

jwt:
  secret: your-secret-key
  expiration: 24h
